details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    realign: false
    recalibrate: false
    mark_duplicates: true
    save_diskspace: true
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    tools_off:
    - gatk4
    variantcaller:
    - gatk-haplotype
  analysis: variant2
  description: '912R_A337376'
  files:
  - /hpf/largeprojects/ccmbio/naumenko/project_cheo/912R/input/912R_A337376.bam
  genome_build: GRCh37
  metadata:
    batch: 912R
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
