details:
- algorithm:
    aligner: false
    effects: vep
    effects_transcripts: all
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - samtools
    - freebayes
    - platypus
    ensemble:
      numpass: 2
    validate: giab-NA12878/truth_small_variants.vcf.gz
    validate_regions: giab-NA12878/truth_regions.bed
  analysis: variant2
  description: 'gatk4_validation'
  files:
  - /hpf/largeprojects/ccmbio/naumenko/validation/WGS_NA12878/input/WGS_NA12878_1.fq.gz
  - /hpf/largeprojects/ccmbio/naumenko/validation/WGS_NA12878/input/WGS_NA12878_2.fq.gz
  genome_build: GRCh37
resources:
  default:
    cores: 1
    jvm_opts:
    - -Xms75m
    - -Xmx700m
    memory: 1G
upload:
  dir: ../final
